#### 1.What are the two values of the Boolean data type? How do you write them?

Two values of boolean data type is :

1. True

2. False

We can Write by by using bool()

In [6]:
#another way is:

bool(1)

True

In [7]:
bool(0)

False

#### 2. What are the three different types of Boolean operators?

1. and

2. or

3. not

#### 3. Make a list of each Boolean operator&#39;s truth tables (i.e. every possible combination of Boolean values for the operator and what it evaluate ).

In [1]:
#and
import numpy as np
x = [[0,0,0],
 [0,1,0],
 [1,0,0],
 [1,1,1]
]

print(np.array(x))

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


and operator says that value is true if and only if both values are true if compared

eg: x=1
    
    y=1
    
here x and y is true so value is true

In [2]:
#or
y = [[0,0,0],
 [0,1,1],
 [1,0,1],
 [1,1,1]
]

print(np.array(y))

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


or operator says that value is true if any of both values are true if compared

eg: x=1
    
    y=0

here x is True and y is False still values will be True

In [4]:
#not
z = [[0,1],
 [1,0],
]

print(np.array(z))

[[0 1]
 [1 0]]


in not operator if one value is true another value will be false

eg: if x =1
    
    then y=0
    
    and vice versa

#### 4. What are the values of the following expressions?

In [5]:
(5 > 4) and (3 == 5)

False

In [6]:
not (5 > 4)

False

In [7]:
(5 > 4) or (3 == 5)

True

In [8]:
not ((5 > 4) or (3 == 5))

False

In [9]:
(True and True) and (True == False)

False

In [10]:
(not False) or (not True)

True

#### 5. What are the six comparison operators?


In [ ]:
#1. > (greater than)

#2. < (lesser than)

#3. >= (greater than equal to)

#4. <= (lesser than equal to)

#5. == (equal to equal to)

#6. <> (not equal to)

#### 6. How do you tell the difference between the equal to and assignment operators?Describe a condition and when you would use one.

assignment operator is used to assign a value to a variable
eg: a =10

equal to operator is used to compare two values or variables

eg: 5 == 5

In [11]:
x = 5 #assignment operator
y = 5

if x == y:  #equal to operator
    print("perfect")

perfect


#### 7. Identify the three blocks in this code:

In [13]:
spam = 0
if spam == 10:
    print('eggs')
if spam > 5:
    print('bacon')
else:
    print('ham')
    print('spam')
    print('spam')

ham
spam
spam


block 1: if spam == 10:
            
            print('eggs')

block 2: if spam > 5:
            
            print('bacon')
            
block 3: else:
            
            print('ham')
            
            print('spam')
            
            print('spam')

#### 8. Write code that prints Hello if 1 is stored in spam, prints Howdy if 2 is stored in spam, and prints Greetings! if anything else is stored in spam.

In [15]:
spam = int(input("enter a number "))
if spam == 1:
    print("Hello")
elif spam ==2:
    print("Howdy")
else:
    print("Greetings!")


enter a number 1
Hello


In [16]:
spam = int(input("enter a number "))
if spam == 1:
    print("Hello")
elif spam ==2:
    print("Howdy")
else:
    print("Greetings!")

enter a number 2
Howdy


In [17]:
spam = int(input("enter a number "))
if spam == 1:
    print("Hello")
elif spam ==2:
    print("Howdy")
else:
    print("Greetings!")

enter a number 3
Greetings!


In [21]:
#another version
spam = input()
if spam == "1":
    print("Hello")
elif spam =="2":
    print("Howdy")
else:
    print("Greetings!")

1
Hello


In [22]:
spam = input()
if spam == "1":
    print("Hello")
elif spam =="2":
    print("Howdy")
else:
    print("Greetings!")

2
Howdy


In [23]:
spam = input()
if spam == "1":
    print("Hello")
elif spam =="2":
    print("Howdy")
else:
    print("Greetings!")

friend
Greetings!


#### 9.If your programme is stuck in an endless loop, what keys you’ll press?

break

#### 10. How can you tell the difference between break and continue?

break stops the loop

continue skips the that particular iteration and continues with next iteration.

In [33]:
a = [1,2,3,4]

for i in a:
    print(i)
    break
    
print("iteration stopped because of break")

1
iteration stopped because of break


In [31]:
a = [1,2,3,4]

for i in a:
    if i == 2:
        continue
    print(i)
else:
    print("number 2 is not printed because of continue")

1
3
4
number 2 is not printed because of continue


#### 11. In a for loop, what is the difference between range(10), range(0, 10), and range(0, 10, 1)?

In [40]:
x = range(10)

for i in range(10):
    print(i, end="")

0123456789

In [37]:
x = range(0,10)

for i in range(0,10):
    print(i, end="")

0123456789

In [38]:
x = range(0,10,1)

for i in range(0,10,1):
    print(i, end="")

0123456789

basically they are all same

#### 12. Write a short program that prints the numbers 1 to 10 using a for loop. Then write an equivalent program that prints the numbers 1 to 10 using a while loop.

In [41]:
z = range(1,11)

for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [46]:
b = 0
c = 10
while b < c:
    b += 1
    print(b)

1
2
3
4
5
6
7
8
9
10


#### 13. If you had a function named bacon() inside a module named spam, how would you call it after importing spam?

buy using dot operator

eg: spam.bacon()